### ISSUE TITLE
Module resolution fails on symlinked dependency

### ISSUE THREAD

**Issue by TheOzim** [monounity/karma-typescript#324]
First of all, thanks for the great work on karma-typescript!

I am not sure, if this is an issue with my configuration, karma-typescript or one of its dependencies.

## Description

I have been running into an issue with resolving symlinked dependencies (using relative path dependencies in npm).

The main issue seems to be, that the symlink is resolved in some situations, but not all.

I created a small repository to reproduce the issue: https://github.com/TheOzim/karma-typescript-issue.

## Details

`module-a` gets hooked into `module-b` using symlinks and the symlink gets resolved for the require lookup only - not for the entry in the `commonjs` `global.wrappers` array.

When debugging `karma-typescript/dist/client/commonjs.js` `module-a` is registered as `<absPath>/module-b/node_modules/module-a/src/index.ts`, as one would expect.

But when the require of `module-a` is resolved in `module-b/src/lib/Add.ts`, the filename used for the lookup is `<absPath>/module-a/src/index.ts`.

Therefore, the `module-a` cannot be resolved and the execution fails.

## Misc

I tried all kinds of configuration options in various different combinations, but could not get it to work. I.e. bundleOptions.resolve.alias/directories did not seems to have any effect.

I hope you might be able to point me into the right direction or identify the underlying issue.
Thanks in advance!

**Comment by erikbarke** [comment]
It could be a side effect of #234, but it also looks like this one, #316, which was solved in #323. Does it work if you run the version in #323?

**Comment by TheOzim** [comment]
Thanks for the quick reply. I will give it a try as I get around to it and report back

**Comment by TheOzim** [comment]
@erikbarke The PR does not resolve issue. I am still seeing the exact same behavior as before.

**Comment by mavarazy** [comment]
Worked for me, when included simlinked repository in `files` and `preprocessors` section

```js
...
files: [
     ...,
     { pattern: '../module/src/**/*.ts' },
],
preprocessors: {
     '../module/src/**/*.ts': ['karma-typescript'],
},
```

**Comment by TheOzim** [comment]
Thanks @mavarazy for sharing the workaround.

I still think this should be fixed, as the workaround requires maintaining the path to the symlinked packages in multiple places:
- tsconfig.json
- karma.config.json
- package.json (when using relative paths for the modules)
