### ISSUE TITLE
How to test with ES2017 dependency?

### ISSUE THREAD

**Issue by vidartf** [monounity/karma-typescript#344]
This issue is more of a reference for how I resolved an issue, but with some actionable points at the end.

One of my dependencies recently started shipping ES2017 syntax modules. Now, when trying to update my package to use the updated dependency, my tests failed with the following error:
```
ERROR [source-reader.karma-typescript]:
Error parsing code:
Unexpected token (30:10) ...
< code featuring object destructuring >`
```

After a lot if trial and error, the solution was to both add the es6 transforms, and then set the acorn ecmaVersion to 8 (es2017):

```json
bundlerOptions: {
  acornOptions: {
    ecmaVersion: 8,
  },
  transforms: [
    require("karma-typescript-es6-transform")()
  ]
}
```

Noteworthy points:
- I found out by inspecting the code that the "ES6" transforms use the same acorn options as the main package, so it can be made to transform ES2017 by configuring the acornOptions.
- Since the `acornOptions` ended up being critical again, it should either be documented, or a proxy value for `acornOptions.emcaVersion` should be specified. Alternatively, the default version for the `ecmaVersion` should be raised, but this will then become a recurring source of issues as new JS versions are added.

**Comment by erikbarke** [comment]
Nice work! This is indeed an undocumented feature, and I vaguely recall the rationale for this being that acorn is such an integral part of the core that end users really shouldn't be able to change the config, but I guess that's a moot point now. I'll add this to the documentation, thanks ☺️

**Comment by vidartf** [comment]
You don't necessarily have to expose the full config, but allowing the user to specify the ECMA version is very useful at least (you could add an alias directly on `bundlerOptions`). I don't fully understand the trade-offs though, so I'll happily accept what you decide (thanks for giving the undocumented escape hatch in the meanwhile though).

**Comment by vidartf** [comment]
Hmm. On a different project, I'm getting the following error using the setup described above:

```
23 07 2019 13:52:59.900:INFO [Firefox 68.0.0 (Windows 10.0.0)]: Connected on socket Hhs6J02z9u6SAIHPAAAA with id 93641912
Firefox 68.0.0 (Windows 10.0.0) ERROR
  ReferenceError: regeneratorRuntime is not defined
  at C:/Users/.../AppData/Local/Temp/karma-typescript-bundle-126841qw5oHXMkhZf.js:18220:18
```

Is this a babel dependency that I should add, or is this something the transform package should add?

**Comment by vidartf** [comment]
(I resolved that other issue by configuring babel like this:)

```js
require("karma-typescript-es6-transform")({
 presets: [
  ["env", {
   "targets": {
    "browsers": ["last 2 Chrome versions"]
   }
  }]
 ]
})
```

**Comment by vidartf** [comment]
I fixed the last issue as well with the following config:

```js
require("karma-typescript-es6-transform")({
 presets: [
  ["env", {
   targets: {
    browsers: ["last 2 Chrome versions"]
   }
  }]
 ]
})
```

This ensures that the right runtime objects are included (don't ask me how or why).

**Comment by andreas-aeschlimann** [comment]
We had the same issue in our project. However, this flag only fixed the `async` keyword issue for us. I still get a problem with the spread operator:

```
Error parsing code: Unexpected token (1054:2) in `/node_modules/jsonld/lib/jsonld.js` at line 1054, column 2:

... ...defaults
}) {
  return Object.assign({}, {docum ...
```

This refers to this line:

```
function _setDefaults(options, {
  documentLoader = jsonld.documentLoader,
  ...defaults
}) {
  return Object.assign({}, {documentLoader}, defaults, options);
}
```

This is the only part which seems to fail in the compilation. Any idea how to make this work?

**Comment by simonvizzini** [comment]
Hi @andreas-aeschlimann I have the same problem with the spread operator. Have you found a solution?

**Comment by andreas-aeschlimann** [comment]
We have not yet, unfortunately.

**Comment by ryanio** [comment]
To fix my issue with the spread operator I used:

```
transforms: [
  require('karma-typescript-es6-transform')({
   plugins: ['@babel/plugin-transform-spread'],
  }),
],
```

**Comment by raushan9108** [comment]
anyone find any solution for this problem, please suggest. This is a very frequent problem, there should be a proper solution for it. I searched everywhere but not much information was available. I have tried all the above suggestions but it's not working.

**Comment by abhinavhiwanj** [comment]
Hi @raushan9108, did you find any workaround for the issue?

**Comment by raushan9108** [comment]
After a lot of tryouts, the below settings worked for me. The above suggestion didn't work for me. I would suggest if you run into such issues, start over again and try with very minimal configuration.

            bundlerOptions: {
                acornOptions: {
                    ecmaVersion: 8,
                },
                transforms: [require("karma-typescript-es6-transform")({
                    presets: [require("@babel/preset-env")],
                    plugins: ["@babel/transform-runtime"]
                })],
                constants: {
                    "process.env": {
                        "PUBLIC_URL": "./base/public"
                    }
                }
            },

**Comment by dzsodzso63** [comment]
It does not work for me. `Error parsing code: Unexpected token`
The code line is:
```
const { message, errors, ...rest } = err !== null && typeof err === 'object' ? err : _data;
```
I use in Node 16
my conf is:
```
    karmaTypescriptConfig: {
      tsconfig: 'config/tsconfig.karma.json',
      bundlerOptions: {
        acornOptions: {
          ecmaVersion: 8,
        },
        transforms: [
          require('karma-typescript-es6-transform')({
            presets: [['@babel/preset-env', { targets: { node: 'current' } }]],
          }),
        ],
      },
    },
```

I tried it in many ways but hard to understand what makes difference as i'd think that the above code should work natively anyways
