### ISSUE TITLE
Help Needed: Can't get past "Cannot find module 'process/browser' from '.'"

### ISSUE THREAD

**Issue by Belciu** [monounity/karma-typescript#84]
Hello,

I can't get past "Cannot find module 'process/browser' from '.'" error. My stack is:

- `karma-typescript@2.1.7`
- Typescript 2.1.5
- node v7.5.0
- npm 4.1.2
- macOS Sierra v10.12.2

I've also aditionally installed the newest `browser-resolve`, `detective`, `buffer`, `process`. Error is the same:

```
[13:16:18] Starting 'run-tests'...
03 02 2017 13:16:19.530:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.1.5

START:
03 02 2017 13:16:24.691:INFO [compiler.karma-typescript]: Compiled 525 files in 4348 ms.
03 02 2017 13:16:25.290:ERROR [karma]: Error: Cannot find module 'process/browser' from '.'
    at Function.module.exports [as sync] (/Users/unknow/projects/gulp/node_modules/resolve/lib/sync.js:33:11)
    at Function.resolve.sync (/Users/unknow/projects/gulp/node_modules/browser-resolve/index.js:321:21)
    at resolve (/Users/unknow/projects/gulp/node_modules/karma-typescript/lib/bundler.js:263:50)
    at resolveModules (/Users/unknow/projects/gulp/node_modules/karma-typescript/lib/bundler.js:242:9)
    at createGlobals (/Users/unknow/projects/gulp/node_modules/karma-typescript/lib/bundler.js:194:9)
    at writeBundleFile (/Users/unknow/projects/gulp/node_modules/karma-typescript/lib/bundler.js:161:21)
    at bundleWithoutLoader (/Users/unknow/projects/gulp/node_modules/karma-typescript/lib/bundler.js:114:9)
    at invokeFunc (/Users/unknow/projects/gulp/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/Users/unknow/projects/gulp/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/Users/unknow/projects/gulp/node_modules/lodash.debounce/index.js:195:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at getCoverage (/Users/unknow/projects/gulp/src/gulp_src/unit-test-runner.js:27:21)
    at /Users/unknow/projects/gulp/src/gulp_src/unit-test-runner.js:88:7
    at removeAllListeners (/Users/unknow/projects/gulp/node_modules/karma/lib/server.js:380:7)
    at /Users/unknow/projects/gulp/node_modules/karma/lib/server.js:391:9
    at Server.close (net.js:1497:9)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:186:7)
    at emitCloseNT (net.js:1543:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Please let me know if theres any other info that would help. Thanks in advance!

**Comment by erikbarke** [comment]
Hey @Belciu, what does your project structure look like and in what directory did you execute the `npm install process ...`?

**Comment by bmontgom** [comment]
@erikbarke sorry for resurrecting a closed post, but as it was never resolved I figured I'd just add on here. I am having the exact same problem. 

<pre>
[17:40:02] Starting 'test'...
[32m19 03 2017 17:40:02.986:INFO [compiler.karma-typescript]: [39m Compiling project using Typescript 2.2.1
[32m19 03 2017 17:40:05.184:INFO [compiler.karma-typescript]: [39m Compiled 35 files in 1618 ms.
[31m19 03 2017 17:40:05.698:ERROR [karma]: [39m[Error: Cannot find module 'process/browser' from '.']</pre>

[I've uploaded the full error output separately (txt file)](http://puu.sh/uQDQ7/13a692af08.txt)

To go ahead and answer the question you asked of @Belciu, I execute the npm install process in my root directory, and my project structure looks like the following:

<pre>
client/ --contains all the source for my project - I know this is atypical
gulp/
node_modules/
gulpfile.js -- loads tasks from gulp directory
karma.conf.js
package.json
tsconfig.jsonx
typings.json
</pre>

I have the _client_ directory specified in my _karma.conf.js_ file, which is below:
<pre>
module.exports = function(config) {
    config.set({
        frameworks: ['jasmine', 'karma-typescript'],
        files: [
            {pattern: 'client/**/*.ts' }
        ],
        preprocessors: {
            '**/*.ts': ['karma-typescript']
        },
        reporters: ['progress', 'karma-typescript'],
        browsers: ['PhantomJS'],
        karmaTypescriptConfig: {
            tsconfig: './tsconfig.json'
        },
        logLevel: config.LOG_INFO
    });
}</pre>

**Comment by erikbarke** [comment]
Hey @bmontgom, it looks like you both run your tests through `gulp`, does your gulp task start a Karma server programmatically?

**Comment by chrisie** [comment]
@erikbarke Sorry for hijacking the question but I also have a similar problem. In my case the error is 
`Unable to resolve module [process/browser] from [bundle/node-globals]`
I am starting the Karma server programmatically in my gulp task (using `require('karma').Server`) but I am getting the exact same error if I start Karma through the command line (`karma start my_config.js`) instead of using a gulp task.

**Comment by Belciu** [comment]
I solved the following problem by switching to `webpack`, `karma-webpack` and `awesome-typescript-loader`

**Comment by psyrendust** [comment]
@Belciu Can you link to an example setup using `webpack`, `karma-webpack` and `awesome-typescript-loader`?

**Comment by erikbarke** [comment]
@bmontgom, @chrisie, I'm flying blind here... Could you create an "empty" version of your projects, ie without `node_modules` and with the source code replaced with just a dummy `.ts` file and post a compressed (zip, gzip, 7zip etc) version here?

I'll try to add a bit more error logging on my end aswell.

**Comment by bmontgom** [comment]
@erikbarke I'll get back to you this evening after I get home from work. Thanks for helping out.

**Comment by erikbarke** [comment]
If you install from the master branch now, `npm i github:monounity/karma-typescript`, the error message should be a bit more meatier, I hope this will help track down this bug.

**Comment by bmontgom** [comment]
@erikbarke With the master branch install I get a missing log4js dependency error. After manually installing that, it's back to the process/browser error again. This time it is slightly different as it says 
<pre>[process/browser] from [bundle/node-globals]</pre>

[Full error output](http://puu.sh/uSC3T/ced22089a3.txt)

**Comment by bmontgom** [comment]
[Updated errors after those last two commits.](http://puu.sh/uSDjH/728485a9ac.txt)

Looks like you may need to add an explicit dep for `base64-js`, `ieee754`, and `isarray`.

**Comment by bmontgom** [comment]
Manually installing those seems to have fixed it. Thanks! I guess we shouldn't mark this as closed though until you can add those dependencies so that people can just install the one `karma-typescript` package.

**Comment by erikbarke** [comment]
Thanks for all your work @bmontgom, it looks like we're on the verge of finally resolving this issue!!

This is what's so weird about this issue, `base64-js`, `ieee754`, and `isarray` are explicit dependencies in the package.json for the `buffer` browser module, but for some reason `npm` won't pull in those modules automatically on some systems... Also, `browser-resolve` seems to fail to resolve those modules on those systems.

The code works on my laptop, in several integration and example projects on [Travis](https://travis-ci.org/monounity), [Appveyor](https://ci.appveyor.com/projects), in real-world projects like [Cycle.js](https://github.com/cyclejs/cyclejs), but fails mysteriously in some environments which has made this issue so elusive, I have never been able to reproduce it!

I'll add the deps tonight, here's to hoping 😃

**Comment by chrisie** [comment]
@erikbarke The issue in my environment was also resolved when I installed the dependencies manually. In case it helps with debugging I am running Node 4.6.0 (using NVM), NPM 2.15.9 and OSX 10.12.3.

**Comment by erikbarke** [comment]
@chrisie, it seems this error is mostly affecting users on older versions of `npm`, I've added your setup to the troubleshooting section of the README.md, thanks!

**Comment by erikbarke** [comment]
@bmontgom, I've added the dependencies now! And of course, your example project runs on my laptop, no bundler errors...

**Comment by bmontgom** [comment]
No problem, thanks for your work on this package. Hopefully this is resolved now.

**Comment by sgen** [comment]
I ran into this issue this afternoon, Its still persisting after installing `process`, `buffer`, `base64-js`, `ieee754`, and `isarray`. Even on the master branch pulled from github. Heres my (repo)[https://github.com/sgen/test-jquery.ts/tree/issue/karma-typescript-84]
