### ISSUE TITLE
support junit test report

### ISSUE THREAD

**Issue by stevez** [monounity/karma-typescript#98]
I want to generate junit xml test report for typescript, for example,
I used the following for javascript unit test:

https://github.com/karma-runner/karma-junit-reporter
or
https://www.npmjs.com/package/karma-sonarqube-unit-reporter

I wonder how to use them in TypeScript?

**Comment by erikbarke** [comment]
Hey @stevez, this sounds like something `karma-typescript` should have, at least a junit reporter!

**Comment by francoislg** [comment]
Pretty much worked OOTB with `karma-junit-reporter` and this simple configuration:

```
{
    frameworks: ["jasmine", "karma-typescript"],
    files: [
        { pattern: "src/**/*.ts" },
        { pattern: "tests/**/*.ts" }
    ],
    preprocessors: {
        "**/*.ts": ["karma-typescript", "coverage"],
    },
    reporters: ["coverage", "spec", "junit"],
    browsers:["PhantomJS"]
};
```

**Comment by erikbarke** [comment]
Solved by the community, awesome! Thanks @francoislg :tada:

**Comment by Hobart2967** [comment]
Uhmm... Still not working for me, I dont get any outputs with this config you provided :\

+1 for support!
